openapi: 3.1.0
info:
  title: Company API
  version: 1.0.0
  description: API for managing companies

paths:
  /:
    get:
      summary: Health check
      responses:
        '200':
          description: Returns a hello message
          content:
            text/plain:
              schema:
                type: string
                example: Hello
    post:
      summary: Create a new company
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Company'
      responses:
        '200':
          description: Company added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Company Added
        '400':
          description: Error adding company
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string

components:
  schemas:
    Company:
      type: object
      required:
        - name
        - shortname
      properties:
        name:
          type: string
        shortname:
          type: string
        active:
          type: boolean